steps:

- steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/my-project2510/my-image:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/my-project2510/my-image:latest']

options:

  logging: 'CLOUD_LOGGING_ONLY'
